# https://starship.rs/config

# Prompt order
format = """
$shlvl\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$cmake\
$nodejs\
$dart\
$dotnet\
$golang\
$java\
$kotlin\
$perl\
$php\
$python\
$ruby\
$rust\
$swift\
$package\
$memory_usage\
$env_var\
$time\


$line_break\
$username\
$hostname\
$character\
$directory\
[\\$ ](white)
$status"""

# Don't print a new line at the start of the prompt
add_newline = true
# right_format = """$all"""

#[line_break]
#disabled = true


[nodejs]
disabled = true
format = "[$symbol]($style)[$version ](dimmed white)"
style = "green"

# Disable the package module, hiding it from the prompt completely
[package]
format = "[$symbol$version]($style) "
# symbol = "@"
style= "dimmed white"


# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[→](white)"    # The "success_symbol" segment is being set to "➜" with the color "bold purple"
error_symbol = "[✗](#FF7C7C)"

[directory]
truncate_to_repo = false
# truncation_symbol = "…/"
truncation_length = 2 # only show current and parent dir
style = "#16B174"


[hostname]
format = "[$hostname ]($style)"
ssh_only = false
style = "#E94AA9"

[git_branch]
format =  "[$symbol$branch]($style) "
style = "#79c0ff"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "conflict"
# disabled = true
style = "dimmed white"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
staged.enabled = true
staged.style = "#7ee787"
staged.value = "++"
