# https://starship.rs/config

# Don't print a new line at the start of the prompt
add_newline = false

# Prompt order
format = """
$all \
$line_break\
$username\
$hostname\
$character\
$directory\
[\\$ ](white)
$status"""

# right_format = """$all"""

# Don't show Google Cloud account
[gcloud]
disabled = true

[nodejs]
disabled = true
format = "[$symbol]($style)[$version ](dimmed white)"
style = "green"

# Disable the package module, hiding it from the prompt completely
[package]
format = "[$symbol$version]($style) "
# symbol = "@"
style= "#8193B2"

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](white)"    # The "success_symbol" segment is being set to "➜" with the color "bold purple"
error_symbol = "[✗](#FF7C7C)"

[directory]
truncate_to_repo = false
# truncation_symbol = "…/"
truncation_length = 2 # only show current and parent dir
style = "#16B174"

[hostname]
format = "[$hostname ]($style)"
ssh_only = false
style = "#E94AA9"

[git_branch]
format =  "[on $symbol](#8193B2)[$branch]($style) "
style = "white"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "conflict"
style = "#8193B2"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
staged.enabled = true
staged.style = "#7ee787"
staged.value = "++"
