# Prompt order
format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$cmake\
$dart\
$dotnet\
$golang\
$java\
$kotlin\
$nodejs\
$perl\
$php\
$python\
$ruby\
$rust\
$swift\
$memory_usage\
$env_var\
$time\
$package\

$line_break\
$character\
$directory\
$status"""

# Don't print a new line at the start of the prompt
add_newline = false

#[line_break]
#disabled = true

[node]
disabled = true

[directory]
style = "bold green"


# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold purple)"    # The "success_symbol" segment is being set to "➜" with the color "bold purple"
error_symbol = "[➜](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
format = "[$symbol$version]($style) "

[host]
# disabled = true
format = "[$hostname]($style) in "

[git_branch]
format =  "on [$symbol$branch]($style) "
style = "bold blue"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "conflict"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
staged_count.enabled = true
staged_count.style = "green"
staged.style = "green"
staged.value = "++"

